name: HoloIRC
markdown: kramdown
highlighter: rouge
category-list: [features]
permalink: pretty
baseurl: "https://holoirc.com"
mainsiteurl: "https://holoirc.com"

plugins:
  - jekyll-redirect-from

exclude: ["CNAME", "README.md"]